--Tao db QLQA


CREATE TABLE users(
	user VARCHAR(50),
	password VARCHAR(50)
);

CREATE TABLE img(
	id INT,
	Anh VARCHAR(255)
);

CREATE TABLE GioHang(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia INT		
);

CREATE TRIGGER gio_hang AFTER INSERT ON GioHang
FOR EACH ROW
	INSERT INTO img(id,Anh)
    VALUES (NEW.id,NEW.Anh);

CREATE TABLE DoNu(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia INT		
);
CREATE TRIGGER do_nu AFTER INSERT ON DoNu
FOR EACH ROW
    INSERT INTO GioHang(id,Anh,Gia)
    VALUES (NEW.id,NEW.Anh,NEW.Gia);



CREATE TABLE DoDoi(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia INT		
);

CREATE TRIGGER do_doi AFTER INSERT ON DoDoi
FOR EACH ROW
    INSERT INTO GioHang(id,Anh,Gia)
    VALUES (NEW.id,NEW.Anh,NEW.Gia);


CREATE TABLE PhuKien(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia INT		
);
CREATE TRIGGER phu_kien AFTER INSERT ON PhuKien
FOR EACH ROW
    INSERT INTO GioHang(id,Anh,Gia)
    VALUES (NEW.id,NEW.Anh,NEW.Gia);

INSERT INTO users
	VALUES('vananh','123');