--Tao db QLQA


--Tao user dang nhap

CREATE TABLE users(
	email VARCHAR(50),
	password VARCHAR(50)
);

--TAO BANG Do Nu
CREATE TABLE DoNu(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia VARCHAR(255)		
);

--TAO BANG Do DOI
CREATE TABLE DoDoi(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia VARCHAR(255)		
);


--TAO BANG PHU KIEN
CREATE TABLE PhuKien(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia VARCHAR(255)		
);


--them user
INSERT INTO users
	VALUES('truong','123')