--Tao db QLQA


CREATE TABLE users(
	user VARCHAR(50),
	password VARCHAR(50)
);
CREATE TABLE GioHang(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia INT		
);


CREATE TABLE img(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255)
);

CREATE TABLE DoNu(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia INT		
);
CREATE TRIGGER do_nu AFTER INSERT ON DoNu
FOR EACH ROW
    INSERT INTO GioHang(id,Anh,Gia)
    VALUES (NEW.id,NEW.Anh,NEW.Gia);
CREATE TRIGGER do_nu2 AFTER INSERT ON DoNu
FOR EACH ROW
	INSERT INTO img(id,Anh)
    VALUES (NEW.id,NEW.Anh);


CREATE TABLE DoDoi(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia INT		
);

CREATE TRIGGER do_doi AFTER INSERT ON DoDoi
FOR EACH ROW
    INSERT INTO GioHang(id,Anh,Gia)
    VALUES (NEW.id,NEW.Anh,NEW.Gia);
CREATE TRIGGER do_doi2 AFTER INSERT ON DoDoi
FOR EACH ROW
	INSERT INTO img(id,Anh)
    VALUES (NEW.id,NEW.Anh);

CREATE TABLE PhuKien(
	id INT PRIMARY KEY AUTO_INCREMENT,
	Anh VARCHAR(255),
	Gia INT		
);
CREATE TRIGGER phu_kien AFTER INSERT ON PhuKien
FOR EACH ROW
    INSERT INTO GioHang(id,Anh,Gia)
    VALUES (NEW.id,NEW.Anh,NEW.Gia);
CREATE TRIGGER phu_kien2 AFTER INSERT ON PhuKien
FOR EACH ROW
	INSERT INTO img(id,Anh)
    VALUES (NEW.id,NEW.Anh);

INSERT INTO users
	VALUES('vananh','123');